### PR TITLE
Update and proofread the Castilian Spanish translation file

### PR DESCRIPTION
**Pull request by Swyter**
Fix a few typos and awkward phrasing by non-natives. Adjust wording to meet the tight space limitations without losing information. Should be good to go.

* **Please check if the PR fulfills these requirements**
- [x] The commit message makes sense
- [ ] The changes have been tested locally
- [ ] Are there any breaking changes

* **What kind of change does this PR introduce?**
Translation update with several improvements.

* **Does this PR introduce a breaking change?**
I sure hope not.

* **Other information**:
Thanks for the clever Web editor tool. I love the philosophy behind these tiny offline pages. I can see that a lot of thought went into the infrastructure.

I haven't made a custom build yet to test, but in general the strings are shorter than in the current one. I have gone through it and tweaked words here and there in various passes until everything fell into place, so hopefully this improves things a bit.

Looks like the first version was done a non-native. It was still pretty serviceable, I think.

Thanks again for the great firmware. Let me know what you think.

### CODE REVIEW

**Comment by Swyter** [comment]
Thanks to the CI runs I have been able to test the generated WIP firmwares (via the provided artifacts) and do even more adjustments. I'm pretty happy with it so far.

**Comment by Swyter** [comment]
@Ralim By the way, looks like #573 introduced `SettingStartSleepOffChar` (the `O` option) but from what I've seen it isn't referenced in the scrolling description yet. Added it anyway. ¯\\\_(ツ)_/¯

Also, if `ResetOKMessage` is shorter than the screen width there's only a partial blit, leaving part of the previous warning/scrolling message as background "garbage", pretty minor. See 322573a1.

**Comment by Ralim** [comment]
Are you happy now for this to merge :)

I think your first to really update the languages since 573 :)
I'll have a look into the reset message :)

**Comment by Swyter** [comment]
Hi, @Ralim. I gave it another go today and I'm reasonably confident that things hold up.
Ready to merge, I'll send another pull request if I notice something fishy. ¯\\\_(ツ)_/¯

**Pull request merged**
