### PR TITLE
feat: improve Russian translation

### PR DESCRIPTION
**Pull request by xobotyi**
Made it more accurate, fixed some translation mistakes.

* **Please check if the PR fulfills these requirements**
- [] The commit message makes sense
- [] The changes have been tested locally
- [] Are there any breaking changes

* **What kind of change does this PR introduce?**
Translation improvement

### CODE REVIEW

**Comment by Ralim** [comment]
I'm going to trust this is correct (I have no real way of knowing).

Have you tested this on a device?

**Comment by xobotyi** [comment]
@Ralim sadly have no Linux close to build it.
If you can build it for me I'd like to test it before releasing.

**Comment by Ralim** [comment]
This repo is setup to this for you :)

If you click on the green tick next to the commit you should be able to see the build assets which will include the hex files 😅

If that doesn't make sense let me know and I'll try and write it in step form.

**Comment by xobotyi** [comment]
@Ralim yeet!
didnt even thought it will store artifacts for PR builds😅

**Comment by xobotyi** [comment]
@Ralim tested on TS80, looks good to me

**Pull request merged**
