### PR TITLE
Added a power limit option, a boot logo timeout menu, and fixed some display bugs

### PR DESCRIPTION
**Pull request by aWZHY0yQH81uOYvH**
* **Please check if the PR fulfills these requirements**
- [x] The commit message make sense
- [x] The changes have been tested locally
- [x] No (significant, I hope) breaking changes

* **What kind of change does this PR introduce?**
   - Introduces a power limit feature for the TS100 which can be useful when powering it from USB PD power banks that cannot supply the full amount of power the iron would normally take at 20V. This is something I requested in Issue #497 but decided to try to implement myself.
   - Fixes two minor display bugs when using the detailed idle screen:
      * If you tried to turn the iron on while it is in an undervoltage condition, the voltage was displayed with a "V" at the end which was cut off and produced a weird corrupted character.
      * The voltage display would not update while on the initial idle screen (when the iron is first powered on).

* **What is the new behavior?**
   - There are two new menu options under Advanced Settings:
      * Power limit enable
      * Power limit
   - When power limit enable is checked, the iron will not exceed the power set by the power limit setting. The power limit setting can be set from 5-65 watts in 5-watt increments. (This power is an estimation based on the tip resistance, PWM, and voltage input, so it may not be all that accurate.)
   - When the voltage cutoff is set to anything but "DC," the power limit is disabled. It can be re-enabled after leaving the voltage cutoff menu while any cutoff is set. (This is to automatically disable the limit when you want to power the iron from a LiPo.)
   - The iron defaults to having the power limit disabled and the power limit set to 30 watts.
   - Fixed the aforementioned display bugs.

* **Does this PR introduce a breaking change?** 
   I'm not entirely sure how the translation system works (and I don't speak 25 languages), so I only modified the English translation file and translations_def.js. This means Translation.cpp is missing all the other languages because the Python script doesn't seem to like it when the other languages are missing the new text elements. I hope someone can easily add some placeholders and/or Google Translate some stuff without too much difficulty. I didn't want to break anything.

* **Other information**
   - This was kinda fun. This is my first ever major PR on GitHub. :)
   - I used the command line Makefile because I couldn't get the IDE to work.
   - Here's a compiled HEX file so you can test my changes: [TS100_EN.hex.zip](https://github.com/Ralim/ts100/files/3551532/TS100_EN.hex.zip)

### CODE REVIEW

**Comment by Ralim** [comment]
Hey 👋 glad the PR went well :)

I like what you have done, and all looks basically correct. Last time I had to add to translations I ended up just editing every translation to add the English fallback :'( 

However, as the TS80 is also going to be getting a power limit option as well, could you adjust this to work for both models (ie don't check the soldering iron model) ?

The voltage menu for the TS80 needs some love to be re-worked, but having this in the advanced menu for now makes this a good logical step without much of a change (I hope).

The IDE is now STMCubeIDE as it's much better supported with newer compilers fyi.

**Comment by aWZHY0yQH81uOYvH** [comment]
I've enabled the power limit for the TS80 (basically just removed a bunch of #ifdefs). I don't have a TS80 so I unfortunately can't test it, but here's another set of compiled test files if someone else can: [Power Limit Test.zip](https://github.com/Ralim/ts100/files/3553136/Power.Limit.Test.zip)

As far as I can tell the other power limit option for changing the QC negotiated voltage on the TS80 is an independent and also useful setting, but its name is pretty similar to what I've added. Perhaps it would be good to change this to something like "QC Voltage Select" or something to avoid confusion, like you suggested at the bottom of Issue #462. (It also looks like temperature compensation on the tip resistance would be useful in making the power calculation more accurate.)

I also just copied the English translation to the other languages as you said you did, so all the languages are back in Translation.cpp again.

I saw System Workbench listed as the IDE on the wiki and under another issue so tried to make it work with that. No wonder I kept getting errors complaining about STMCube not existing and "orphaned configurations"... I was quite surprised after going through all that that the makefile just worked perfectly after installing the compiler with Homebrew. :)

**Comment by agatti** [comment]
Does this patch fix the flickering when displaying undervoltage information?  I'm not sure if it's just my iron having this issue, but the flickering is quite noticeable when switching from normal to undervoltage screens (apologies for the OLED glow, it was recorded in a low light environment):

img1
img2
img3
img4

**Comment by aWZHY0yQH81uOYvH** [comment]
Do you mean the soldering screen (with power) flashing very briefly before it switches to the undervoltage screen? If so, my iron also does that. I can look into it.

**Comment by agatti** [comment]
Yep, that's exactly what I meant, thank you :)

**Comment by aWZHY0yQH81uOYvH** [comment]
Fixed the display flashing issue and changed the "Input V" text on the UVLO screen to "Trip V".

I started to make the voltage update live on the UVLO screen because it didn't make sense that "Input V" wouldn't change, but realized that you would want to know what voltage the iron tripped at (as batteries' voltage goes back up after taking a load off). I put it back to being stuck at whatever the UVLO screen tripped at and changed the text to make it more obvious what the voltage represents.

**Comment by aWZHY0yQH81uOYvH** [comment]
Small change: Made the power limit step for the TS80 smaller (2W) because it has a smaller power range and the nominal power levels are divisible by 2, not 5.

Test files: [TS80 Smaller Power Step Test.zip](https://github.com/Ralim/ts100/files/3553446/TS80.Smaller.Power.Step.Test.zip)

**Comment by aWZHY0yQH81uOYvH** [comment]
Added a menu option to allow selectable timeout of boot logo.
Time options: `[Off, 1s, 2s, 5s, 10s, 30s, Inf]`
Requested in Issue #292

**Comment by Ralim** [comment]
Normally I would ask you to create these as seperate pull requests for each individual change where possible.

Are you happy for this to be merged in its current state ?

**Comment by aWZHY0yQH81uOYvH** [comment]
Oh, sorry...

I do think this is ready to merge. I haven't been able to test this with a TS80, but the changes differ very little between the two models so it should be okay.

**Comment by limited660** [comment]
Flashing UVLO Screen Fix Test, TS80 Smaller Power Step Test, and Boot Logo Time Test on a TS80 all result in a flashing screen and unusable device for me.

**Comment by aWZHY0yQH81uOYvH** [comment]
@limited660 Well, good thing you checked on a TS80 I guess! That's strange. The only thing I [changed](https://github.com/aWZHY0yQH81uOYvH/ts100/commit/9dc5fe07ab668191160f9f81d733fbc3e706d767) between "Power Limit Test" and "UVLO Screen Fix Test" is code that should only be included when compiling for the TS100, and added a new text string. Just to confirm, does "Power Limit Test" work fine on your TS80? When the screen is flashing, what does it flash between? Thanks for testing.

**Comment by limited660** [comment]
"Power Limit Test" works, all the later versions result in the screen alternating between off and the idle screen. Holding the button furthest from the tip results in the voltage reading going from 9v to 6v and the temp changing from 300C to 70C.

**Comment by aWZHY0yQH81uOYvH** [comment]
That's a lot of glitchyness for just the simple code change. My first guess would be that something happened during compilation. I think I remember not knowing how to make the Makefile compile for the TS80 for "Power Limit Test," so I changed one line in it to make it compile for the TS80. For the later test files I changed that back and figured out what command line arguments seemed to make it produce a TS80 file. I think I have duplicated what I did when originally compiling "Power Limit Test" to produce this from the latest code in this PR: [Maybe Glitchy TS80 Fix.zip](https://github.com/Ralim/ts100/files/3645173/Maybe.Glitchy.TS80.Fix.zip) (sorry for the terrible file names)

If this new set of files doesn't work, my next guess would be something to do with the flash memory. I haven't looked into the addresses where things are stored yet, but the TS80 BIN file is _slightly_ larger than the TS100 one, which might be causing some kind of conflict...?

I've never developed for the STM32 before, so please forgive me if I'm doing something dumb here.

**Comment by limited660** [comment]
That worked but the TS80 appears to be heating while on the idle screen. I plugged it in, adjusted some settings and calibrated the temperature and when I got back to the idle screen is was up to 40C and the tip was warm.

Are your changes to RC4 or RC5?

**Comment by aWZHY0yQH81uOYvH** [comment]
My changes are to the latest code in this repo, so other changes have been made since RC5.

The slight tip heating may be due to a feature in the TS80 code that periodically puts 5W into the heater for 100ms every 500ms to prevent USB power banks from going to sleep.

**Comment by aWZHY0yQH81uOYvH** [comment]
Looks like the broken TS80 files are exactly the same as the TS100s... So whatever I did to make them just changed the filename instead of the actual model. 🤦‍♂️

**Comment by Ralim** [comment]
@aWZHY0yQH81uOYvH just try using the build script?
Generally it's much easier to keep things re-producable by using the script.

**Comment by aWZHY0yQH81uOYvH** [comment]
Ah. That would make a lot more sense. I just saw the makefile and used it. 

I tried running build.sh, which ran without error and produced all the different translations. However, I checked and the TS80 and TS100 files came out exactly the same again. For some reason it looks like passing things into the make command doesn't work properly on my system (macOS 10.14). (The file name comes out right though...?) So far, the only thing that has successfully produced a TS80 file is temporarily changing line 3 of the makefile to default to the TS80. Regardless, I hope the latest set of files I uploaded are sufficient to test everything.

Are there any tweaks anyone would like me to make to my changes to make them fit in or work better?

**Comment by agatti** [comment]
You can try to use `./build.sh -l EN -m TS80` and `./build.sh -l EN -m TS100` to build both versions of the firmware with just the English localisation built in - you will find built files in `workspace/TS100/Hexfile`.  That's how I built test firmware on my macOS 10.14 installation.

Just make sure to save the content of the `workspace/TS100/Hexfile` directory if you switch models as the build script currently deletes all files there rather than the ones related to the model you passed to the script.  (I'll see if I can fix that later on today)

**Comment by aWZHY0yQH81uOYvH** [comment]
Those commands work and produce the right files if run independantly, but if I just run `./build.sh -l EN` to make it build for both models, it makes two identical sets of files again (with different names). Does it do the same for you on your system?

**Comment by agatti** [comment]
Indeed it does.  I believe what's happening is `make` not recognising the change in #defines and reusing all the object files it can find - which are for a different variant anyway.

**Comment by Ralim** [comment]
@aWZHY0yQH81uOYvH 
Any chance you can re-base these changes so that this is mergable?
Now that CI is setup, should be easier to know if you break the build for any languages.

**Comment by Firebie** [comment]
Diff on latest version:
https://gist.github.com/Firebie/fba43355bc36d61f58b4d7c025f59677

**Comment by Eldenroot** [comment]
Are you planning to merge this? Looks nice !

**Comment by Firebie** [comment]
https://github.com/Ralim/ts100/pull/552

**Comment by Ralim** [comment]
Merged #552. Going to close this one as i believe 552 replaces this one.

**Comment by aWZHY0yQH81uOYvH** [comment]
Looks like #552 only included the power limit stuff. Should I still try to rebase my other changes or have they already been incorporated by other people? I've been meaning to get to this, but I've been busy with school.

**Comment by Ralim** [comment]
Double check as some changes may have been superseded by other changes in the repo as well.

Don't panic, I was tied up with Thesis work for last year which is why i was fairly absent :|

**Comment by braydenhouston** [comment]
Has any progress been made to merge some of these changes? It would be nice to have a logo using this custom firmware. The display issues would be a welcome fix too.

**Comment by Ralim** [comment]
@braydenhouston 
Logo support itself has been in the firmware for well over a year.
Most of the display fixes have made their way in afaik 😅

**Comment by aWZHY0yQH81uOYvH** [comment]
Assuming the display bugs have been fixed, it looks like the only unique thing left from this PR is the logo timeout menu thing. In a few weeks, if people are interested, I could figure out the new code and make another PR with that.

**Pull request closed without merging**
