### PR TITLE
Improve Russian translation

### PR DESCRIPTION
**Pull request by vladkorotnev**
Added new version strings and corrected previous translation

### CODE REVIEW

**Comment by vladkorotnev** [comment]
I wonder how I split the setting name translation into a separate pull request?

**Comment by Ralim** [comment]
Not sure the best way, I just do different branches for different pull requests.
Normally the idea was to leave the short names the same in every language? No real massive reason other than most languages didn't fit the character requirements.

**Comment by vladkorotnev** [comment]
Is it possible for you to somehow merge just the first commit of this then? Or need I roll it back on my side? It really makes it a more intuitive menu for me.

**Comment by SijmenSchoon** [comment]
```bash
git reset --soft HEAD^  # go back one commit
git push --force  # push the changes (need to force)
git checkout -b translate-settings  # create a new branch
git add -A  # or add just the files you want to commit
git commit -m 'Translate settings in RU'  # recommit
git push -u origin translate-settings
```

**Comment by runy1984** [comment]
Ralim
 to do the translation at the suggestion blackarachnia! 
where other functions are translated into Russian language version 2.0 .????

**Comment by Ralim** [comment]
@runy1984 
I'm not entirely sure what you are asking ?

I'm currently away from home for work so I don't currently have a large amount of time to push a new release yet. This will be included in the next one.

**Comment by Ralim** [comment]
I have manually merged this :)
Need to fix up the code to support one section, but otherwise, everything else is in there and working.

Need to do more code to support these guys :
```
const char SettingRightChar = 'П';
const char SettingLeftChar = 'Л';
const char SettingAutoChar = 'A';
```

**Pull request closed without merging**
