### PR TITLE
remove hardcoded MODEL_TS80

### PR DESCRIPTION
**Pull request by dhiltonp**
Also add a #define used by sw4stm32/atollic so that the gui successfully builds.

### CODE REVIEW

**Comment by dhiltonp** [comment]
I can roll back the UI change if you like, I'm not married to it.

Can you also confirm that this line shouldn't have a `break`? 

https://github.com/Ralim/ts100/pull/393/files#diff-9f5b26afccb4998da06f4397dbfd1ee8L692

**Comment by Ralim** [comment]
That line should have a break 😢 
Thanks for the better logic in the #defines,
CNA you throw in the break and I'll merge or I'll just merge and do it here tonight :/

**Comment by dhiltonp** [comment]
done

**Comment by Ralim** [comment]
Legend!
Thanks

**Pull request merged**
