### PR TITLE
Add common IDE files to .gitignore.  Remove tracked files.

### PR DESCRIPTION
**Pull request by Cabalist**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [x] The commit message make sense
- [x] The changes have been tested locally
- [ ] New features have been documented in the Wiki
- [ ] I'm willing to maintain this in the future (Totally Optional)

* **What kind of change does this PR introduce?** 
Bug fix.  Maintenance.

* **What is the current behavior?** 
Currently a number of IDE files are tracked by git.   This can cause issues when users try and use those IDEs with their own settings.

* **What is the new behavior (if this is a feature change)?**
Files are removed and the .gitignore made more restrictive.

* **Does this PR introduce a breaking change?** 
Nope.  You'll keep your files but they will no longer be tracked.

* **Other information**:
Please review.   I believe all the files I removed to be unnecessary.

### CODE REVIEW

**Comment by Ralim** [comment]
@Cabalist 
I have noticed that you are removing the following files that are required (_i believe_) for the projects to be openable in their respective IDE's:

* `.cproject`
* `.project`

Otherwise I'm happy to merge this in.

**Comment by Cabalist** [comment]
Hey there, 

From my reading .cproject and .project are generally discouraged from being committed.   You can still open the project in eclipse by choosing either "File > Import > General > Existing Projects Into Workspace"  or using the wizard and selecting "Create project from existing source"

Some discussion:
https://stackoverflow.com/questions/18955149/ignore-classpath-and-project-from-git
https://stackoverflow.com/questions/44657300/what-project-files-are-supposed-to-ignore-in-gitignore-file

They are also often found in templates .gitignores.   Including[ Github's defaults](https://github.com/github/gitignore/blob/master/Global/Eclipse.gitignore)

**Comment by Ralim** [comment]
@Cabalist 
Sounds good to me, can you re-base or merge with master and then ill merge it in :) (Ignore CI)

**Comment by Cabalist** [comment]
Done.  :)

**Comment by Cabalist** [comment]
Wait.  I don't like the looks of that merge...   I am going to close this and open a new clean PR.

**Comment by Ralim** [comment]
@Cabalist Thank you, yeah that is a bit of an ugly one (my fault for being busy and not getting to this).
Thank you for your effort your putting in :)

**Pull request closed without merging**
