### PR TITLE
Logos

### PR DESCRIPTION
**Pull request by Mrkvozrout**
I created a folder for logos, people want to contribute (mentioned in #182 and #190)

- added `_clear_logo.hex`
- contributed my TS100 logo ts100

Currently there is not a way to remove the logo after you flashed there some. You can now flash the `_clear_logo.hex` to remove existing logo as if it was never used

- no logo showed
- no logo delay (this is not empty logo) - immediatelly starts

### CODE REVIEW

**Comment by Mrkvozrout** [comment]
TODO if this PR is accepted, wiki page `Editing Logo Editor` should be updated with reference to folder with prepared logos and explanation of how to remove logo

**Comment by Mrkvozrout** [comment]
Of course there could be also another menu option to configure logo display time with 0 meaning "logo disabled). I would be happy to implement this but I am not sure if adding new (non critical) menu item with ne translations is good..

**Comment by Ralim** [comment]
So sorry, Never received a notification of this.
I will merge this in this weekend :)

**Comment by discip** [comment]
@Mrkvozrout
@Ralim
Unfortunately the **`_clear_logo.hex`** does not remove a flashed logo!
iron|Firmware Version
-|-
**TS80P**|**https://github.com/Ralim/IronOS/commit/0b623544663ebfab0f6dcf49529720578eed532e**

**Comment by River-b** [comment]
someone in Pinecil reported also does not work for Pinecil to remove a flashed logo.

**Comment by Ralim** [comment]
Yeah this has been logged a few times, the clear logo made as part of the meta repo will work though

**Comment by River-b** [comment]
do you have a link to the one that will work on Pinecil to clear it?

**Comment by Ralim** [comment]
Grab the clear logo file from any action and will work

**Pull request merged**
