### PR TITLE
Add flash script for Linux

### PR DESCRIPTION
**Pull request by awigen**

### CODE REVIEW

**Comment by Ralim** [comment]
Looks great, can you confirm which Linux distributions this will work on?

**Comment by awigen** [comment]
Hi,

I can only confirm it works for me and another person on Fedora.

Cheers,
Alex

**Comment by Ralim** [comment]
Awesome,
Can you just add that to the info on the flash script usage, along with your username so you get credit :)
Then I'll be happy to merge :)

Thanks :)

**Comment by awigen** [comment]
No worries, done.

**Comment by Ralim** [comment]
Thank you :)

**Pull request merged**
