### PR TITLE
ptbr translation revised

### PR DESCRIPTION
**Pull request by ifeghali**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [x] The commit message make sense
- [ ] The changes have been tested locally
- [ ] New features have been documented in the Wiki
- [x] I'm willing to maintain this in the future (Totally Optional)

* **What kind of change does this PR introduce?** 

Translation update. I finally flashed my device with current version and noticed that some strings could be improved for better understanding. 

* **What is the current behavior?** 
(You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** 

No

* **Other information**:

### CODE REVIEW

**Comment by Ralim** [comment]
Any chance you could update this to use the double line format for the text in the settings menu ?
Planning to deprecate the single line modes in the future as flash space gets tighter.

**Comment by ifeghali** [comment]
Sure I can.

**Comment by ifeghali** [comment]
there you go

**Comment by Ralim** [comment]
Thank you :)

**Pull request merged**
