### PR TITLE
Update translations and use new translations infrastructure

### PR DESCRIPTION
**Pull request by jvitkauskas**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [X] The commit message make sense
- [X] The changes have been tested locally
- [X] I'm willing to maintain this in the future (Totally Optional)

* **What kind of change does this PR introduce?** 
- Align Lithuanian translation with text length restrictions
- Update other outdated languages and add all of them to build script
- Fix compilation error by introducing missing "OffString" string to translations
- Adopt results of new translation infrastructure (`Translation.cpp` is generated from translation files)
- Make translation generation script work also with Python 3

* **What is the current behavior?** 
Project does not compile when using generated translation file due to missing "OffString" string

* **What is the new behavior (if this is a feature change)?**
Project does compile

* **Does this PR introduce a breaking change?** 
No?

* **Other information**:

### CODE REVIEW

**Comment by jvitkauskas** [comment]
Still have two languages to add. Please don't merge until I do this.

**Comment by jvitkauskas** [comment]
Added PIDSETTINGS (and other ifdef support for translations). Unfortunately I can't seem to find where those settings are located in menu.

**Comment by Ralim** [comment]
Hi, thank you for this work, especially all the cleanup and updates!

Pidsettings is not going to be supported in future firmware as it was basically just a one off build feature. So don't worry about it not turning up in the firmware. (Which is why it was only in the EN build). I'll check and pull this shortly :)

**Comment by dhiltonp** [comment]
There's an update to HU here: https://github.com/Ralim/ts100/issues/124

**Comment by jvitkauskas** [comment]
Thanks, incorporated into this PR.

**Comment by dhiltonp** [comment]
@jvitkauskas: could you look at #364?

**Pull request merged**
