### PR TITLE
generate power pulses also in soldering and sleep mode

### PR DESCRIPTION
**Pull request by thomasgi1**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [x] The commit message makes sense
- [x] The changes have been tested locally
- [] Are there any breaking changes

* **What kind of change does this PR introduce?**
This is a proposed bug fix for issue #522.

* **What is the current behavior?**
See issue #522

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?**
The PID control is slightly influenced by the additional power pulses.

* **Other information**:
It was a bit hard to find the right settings for the power pulse milliwatts and their duration. I found that the variable milliWattsOut is a misnomer since in realty it is centiWattsOut. For some unknown reason I could not lower the milliWattsOut for power pulse below 2000. Otherwise the power pulses seem to have n effect for the power bank. However, applying the patch to the "testing-temp-rework" work much smoother as the expected minimum power for the power pulses worked also in real world. Unfortunately the "testing-temp-rework" branch had some other issues (the tip temperature was far too low) so that I could not use that branch for my TS80.

### CODE REVIEW

**Comment by Ralim** [comment]
I'm waiting for the `testing-temp-rework` branch to be mergable first before this will go in.

The only thing its waiting on, is making up thermocouple models for the miniware tips (have Hakko and Weller already)

**Comment by Ralim** [comment]
@thomasgi1 
Have you tested this to work locally on any power banks (Could you name them)?
None of my power banks auto-turn-off 😢

**Comment by thomasgi1** [comment]
> @thomasgi1
> Have you tested this to work locally on any power banks (Could you name them)?
> None of my power banks auto-turn-off 😢

Yes, I'm using my own patched version on my TS80 together with a Charmast Powerbank 20800mAh.
Btw. I wondering why the power pulses are only available for the TS80. Is there any reason to not use that mechanism on a TS100? Does the TS100 draw more current when idling?

**Comment by Ralim** [comment]
Awesome,
Can you merge latest master please :) (Not that I think anything will break, but so that CI runs).

> Btw. I wondering why the power pulses are only available for the TS80. Is there any reason to not use that mechanism on a TS100? Does the TS100 draw more current when idling?

Mostly because no-one has asked for it, as most TS100's are powered by DC or via USB-C (Which doesn't go to sleep) its generally of little gain, and just increases power consumption.

**Comment by thomasgi1** [comment]
Merged.

> > Btw. I wondering why the power pulses are only available for the TS80. Is there any reason to not use that mechanism on a TS100? Does the TS100 draw more current when idling?
> 
> Mostly because no-one has asked for it, as most TS100's are powered by DC or via USB-C (Which doesn't go to sleep) its generally of little gain, and just increases power consumption.

That makes sense. Thank you for explanation.

**Pull request merged**
