### PR TITLE
Adjust left limit for drawing

### PR DESCRIPTION
**Pull request by Mrkvozrout**
Do draw area also if just part of it is visible - e.g. do not skip whole letter in rolling description if half of it can be shown.

### CODE REVIEW

**Comment by jonnieZG** [comment]
Good catch, but it needs some tweaking, because there's something funny going on at the rightmost part of the screen, when you run this. I'll take a better look...

**Comment by Mrkvozrout** [comment]
Yes, I just noticed that too and I am here to say:

@Ralim Wait with merge. There's something funny going on at the rightmost part of the screen.

**Comment by Mrkvozrout** [comment]
Fixed, working fine now... (my bad, I am already too tired today)

**Comment by Mrkvozrout** [comment]
I think also the right limit needs fixing. I did not touch that because it seems to work, but the computation is strange. The excess of the wider area should be subtracted from display width, not its X position.

I think it should be:
`visibleEnd = displayWidth - ( (x + width) - displayWidth) = 2 * displayWidth - x + width`

In code:
```
if(x + wide > 96) {
  visibleEnd = 192 - x + wide;
}
```

**Comment by jonnieZG** [comment]
No, @Mrkvozrout, you did it right the first time. Your last edit with (visibleEnd = 192 - x + wide) is *not* correct.

If you rename the variables as following, it will be easier to understand:

```C++
//Draw an area, but y must be aligned on 0/8 offset
// x, y -> screen positions
void OLED::drawArea(int16_t x, int8_t y, uint8_t width, uint8_t height,
		const uint8_t* ptr) {
	// Splat this from x->x+wide in two strides
	if (x <= -width)
		return;    //cutoffleft
	if (x > OLED_WIDTH)
		return;    //cutoff right

	uint8_t iStart = 0;         // starting index within ptr[] (inclusive)
	uint8_t iEnd = width;       // ending index within ptr[] (exclusive)

	// trimming to draw partials
	if (x < 0) {
		iStart -= x;  //subtract negative value == add absolute value
	}

	if (x + width > OLED_WIDTH) {
		iEnd = OLED_WIDTH - x;
	}

...
}
```

**Comment by Mrkvozrout** [comment]
Right, I will get back to the computation later.

@jonnieZG Yesterday I also tried to "draw both line simultaneously" the same way but this has no impact because this part of code just sets pointers in buffer to target data. The buffer is later sent to the OLED via I2C to render. So sadly modifying this code has no effect on the tearing and can stay as it was.

**Comment by Mrkvozrout** [comment]
The right cutoff is correct. Should be:
`visibleEnd = wide - ((x + wide) - displayWidth)`
which equals the current
`visibleEnd = 96 - x`

@Ralim this PR is ready to be merged

**Pull request merged**
