### PR TITLE
Better Bulgarian language translations

### PR DESCRIPTION
**Pull request by dimitroffs**
I have added better translations for Bulgarian language.

### CODE REVIEW

**Comment by Ralim** [comment]
Did you sanity check this using the generated firmware? :sweat_smile: 
If so; happy to merge

**Comment by dimitroffs** [comment]
I will double check it ASAP - used my “kinda” free time (holiday) to put some new translations, but my iron is also resting from me at home! (I am not currently there) ;) I will write again after sanity checks ;)
Regards!

**Comment by Ralim** [comment]
Ahh, makes sense :smile: 

I always appreciate these, as I have no hope of looking after them.
I usually just want a sanity check to make sure they are not cut off or anything weird graphically.
(Compiler will catch the more common issues)

Just let me know when you (or if someone else checks) and if it looks good its good to merge :grin:

**Comment by dimitroffs** [comment]
Hey Ben, 
I have checked new Bulgarian translations on my iron. I have made some tweaks and checked them also. Now everything seems okay. We can proceed with merge :) Regards and thanks once again for help with builds :)

**Comment by Ralim** [comment]
Thank you :)

**Pull request merged**
