### PR TITLE
Use unicode chars U2713/U2717 as true/false in menu

### LINKED ISSUE #168: Use Y/N instead of T/F
It took me a moment to realize what the T/F settings meant... Perhaps it's better to use Y/N (Yes/No) instead?

### PR DESCRIPTION
**Pull request by Mrkvozrout**
Based on latest master (with already replaced T/F chars for check boxes) I tweaked the T/F chars to be:
- true - ✓ - U2713 - check sign
- false -✗ - U2717 - ballot sign

I think it looks neater and even more understandable (as the X looks more descriptive then current empty checkbox):
true
false

resolves #168

### CODE REVIEW

**Comment by ulab** [comment]
I see a small problem with this, the "ballot sign" is used to mark a ballot as selected (hence its name ;)). This on its own might be understood as if the option is enabled. While I agree, that together with the check sign I'd understand which should be what, it might still confuse people at first glance?

The difference between an empty box and a checked box is a more commonly used and understood GUI element.

**Comment by Mrkvozrout** [comment]
Good point. I was not aware of that as the cross without anything else is not commonly used to mark option and crossing something means rejection in my surroundings.

Checkbox is indeed commonly used. I think for the small unicolor display the more simplistic the better. So as the check sign crosses the border of the box on one side and touches on the other side - it just does not look that good on the small scale.

What about simpler bigger checkbox with distinct check mark inside, no crossing and touching? (Or even box with ballot ;) but check sign is nicer imho)

**Comment by ulab** [comment]
I think the check sign is nicer too. I have not uploaded the check sign firmware yet, so I can't say anything about how it looks, but it's probably better to stay inside of the box, yes.

**Comment by Mrkvozrout** [comment]
Implemented bigger and simpler checkboxes, looks great now :)

false
true

**Comment by wortex1979** [comment]
how can i download this firmware?

**Comment by Mrkvozrout** [comment]
@wortex1979 if you know how to compile, you can merge this branch to your repository, or just copy the 2 changed lines (see changed files on the top).

Or here is english version the screenshots were taken from: [TS100.zip](https://github.com/Ralim/ts100/files/1601658/TS100.zip)

**Comment by Rockman18** [comment]
I admit this checkbox looks better than mine ! @Ralim you can merge it if you want !

**Comment by wortex1979** [comment]
@Mrkvozrout tank you. i dont know compile but ı want to learn compline .

**Pull request merged**
