### PR TITLE
Test oled slow speed

### PR DESCRIPTION
**Pull request by paulfertser**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**
(Bug fix, feature, docs update, ...)

* **What is the current behavior?**
(You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by Ralim** [comment]
I generally _dont_ think its the speed of the I2C bus itself.
The OLED is rated to 400kHz and we are already running it a _lot_ slower than that to provide more tolerance. :/

**Comment by paulfertser** [comment]
> I generally dont think its the speed of the I2C bus itself.
> The OLED is rated to 400kHz and we are already running it a lot slower than that
> to provide more tolerance. :/

Understood, but I hoped someone would try it on one of the devices
where it "almost works". I suspect signal integrity issues, probably
lines ringing from too strong pulling down, someone just has to 'scope
the signals to tell what's going on on the "defective" units.

**Comment by Ralim** [comment]
A _very very_ long time ago I made a test firmware with 10kHz signalling without sucsess. Have noticed some of the OLED units I have around here have just "degraded" and the panel itself starts to have issues driving properly.

This _could_ be perhaps that those weaker panels need higher drive voltages / currents but that feels risky to try...hmm...

**Comment by Ralim** [comment]
Going to close this out as it doesnt look like it helped with the issue.

**Pull request closed without merging**
