### PR TITLE
New build.sh script : detect languages with translation_*.json files

### PR DESCRIPTION
**Pull request by Rockman18**
* **Please check if the PR fulfills these requirements**
- [x] The commit message make sense
- [x] The changes have been tested locally
- [ ] New features have been documented in the Wiki
- [x] I'm willing to maintain this in the future (Totally Optional)

* **What kind of change does this PR introduce?** 
New script to generate all *.hex files
```
Usage : ./build.sh [-l <LANG_CODE>] [-m <TS100|TS80>] [-h]

Parameters :
    -l LANG_CODE : Force a specific language (E.g. : EN, FR, NL_BE, ...)
    -m MODEL     : Force a specific model (E.g. : TS100 or TS80)
    -h           : Show this help message

INFO : By default, without parameters, the build is for all platforms and all languages
```

The new script has been tested on git bash on Windows and on Linux

* **What is the current behavior?** 
Each time a new "translation_*.json" file is added by a contributor, the build script has to be updated
The build script impose to build all languages for all models

* **What is the new behavior (if this is a feature change)?**
New script parse "Translation Editor" directory to find all "translation_*.json" files and iterate on those files to detect all available languages 
New script allow to make a build for a specific language and/or a specific model
New script checks if requested language and/or model is available

* **Does this PR introduce a breaking change?** 
n.a

* **Other information**:

### CODE REVIEW

**Comment by Rockman18** [comment]
Hello @Ralim,
Have you test this ? It should be useful to generate the hex files for the next Release without missing any language !!! 

With the last Serbian translation in Cyrillic, it would be helpful to externalize a parameter in json files to add the cyrillic chars in font.h according to the language.

@all : Can I receive feedback in case something doesn't work as expected ?

**Comment by dhiltonp** [comment]
not Ralim, but this looks way more complicated than it needs to be.

Get list of 2-letter language extensions, loop across `lang` and `model`.

**Comment by Rockman18** [comment]
It's not always 2 letters (ex : NL_BE, CS_CZ, SR_LATN....).
And the objective is to detect new files automatically when a contributor add a new language.
This build script doesn't need to be updated when releasing even if a new language has been added.

**Comment by Ralim** [comment]
Hi,
I did indeed miss this earlier on.
Thank you for this, it does look good. I'll give it a whirl under WSL and if all goes well merge it in.

Could you swap it to run over models in the outer loop, slightly more optimal for compiling to avoid the full rebuild each time (working to slowly speed builds)

**Comment by Rockman18** [comment]
Build loop order has been swapped !

**Comment by Ralim** [comment]
@Rockman18 can you merge master back in to sync and then ill merge this in :) 
It may or may not be optimal, but its a step forward :)

**Comment by vomindoraan** [comment]
Wow, I didn't see this PR and I pretty much [rewrote the script](https://github.com/vomindoraan/ts100/commit/ab25904330e3bfd4c777efd48f8701577e7d644d) myself, haha. This looks like it's much more comprehensive, though. I'll be reviewing it sometime soon :smiley:

**Comment by vomindoraan** [comment]
In the mean time, I suggest putting the script through https://shellcheck.net — it's a great tool for finding issues and bugs in shell scripts.

**Comment by Rockman18** [comment]
@vomindoraan Thanks a lot for your version of the script. I use your code for available_languages calculation

@Ralim Ready to be merged

**Pull request merged**
