### PR TITLE
Refactor OLED on/off mechanism.

### PR DESCRIPTION
**Pull request by agatti**
* **Please check if the PR fulfills these requirements**

- [x] The commit message make sense
- [x] The changes have been tested locally
- [ ] Are there any breaking changes

* **What kind of change does this PR introduce?** 

Made the display on/off mechanism a bit more self-descriptive by replacing bare true/false values with an enum with more appropriate value names.

OLED automatic turn-off logic has been cleaned up, along with minor updates to the OLED initialisation sequence.

* **What is the current behavior?** 

The OLED display state management code could have been cleaned up a little.

* **What is the new behavior (if this is a feature change)?**

N/A

* **Does this PR introduce a breaking change?** 

Not really, the code has been refactored to maintain the same user-facing behaviour.

* **Other information**:

### CODE REVIEW

**Comment by Ralim** [comment]
My understanding of the setup code was that it's best to setup the display correctly first incase the power up voltage settings are in states that could "damage" the OLED?

Otherwise happy with merging this :)

**Comment by agatti** [comment]
Well, I've looked at the [datasheet](http://www.i-excellence.com/uploads/201612/585e217f4cc6e.pdf) for the power up sequence.  If the datasheet has to be followed exactly, the current display setup command list isn't 100% correct as it starts with a DISPLAY OFF command rather than a DISPLAY ON (page 11) - however the suggested initialisation sequence starts with a DISPLAY OFF, go figure.

I haven't found any other reference of possible danger in doing things the way this PR suggests, but I'll change that bit just in case.

**Comment by agatti** [comment]
Now that I look at it again, the offending line of code in the setup phase touches the command sequence in the refresh display procedure - so disregard what I've said earlier, this should be functionally equivalent to how it used to be.

**Comment by Ralim** [comment]
Apologies for the delay in merging this :sweat:

**Pull request merged**
