### PR TITLE
Lowering min temp to 10C

### PR DESCRIPTION
**Pull request by Firebie**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [x] The commit message makes sense
- [] The changes have been tested locally
- [] Are there any breaking changes

* **What kind of change does this PR introduce?**
(Bug fix, feature, docs update, ...)
Lowering min temp from 50C to 10C

* **What is the current behavior?**
(You can also link to an open issue here)
https://github.com/Ralim/ts100/issues/620

* **What is the new behavior (if this is a feature change)?**
User can select 10C as min temp for soldering/sleep

* **Does this PR introduce a breaking change?**
(What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by Ralim** [comment]
Is this stable?
Originally the reason i limited the minimum to 50C was that the PID was unstable below that temperature when running off 24V input.

**Comment by Firebie** [comment]
Checked 40C - works fine.

**Comment by Ralim** [comment]
Ah sorry, didn't merge this before i did the other one. Could you merge master in and then ill accept this in :)

**Comment by Firebie** [comment]
I re-based against master

**Pull request merged**
