### PR TITLE
Add utf-8 capable 6x8 pixel small font

### PR DESCRIPTION
**Pull request by matmemo**
This pull request also changes the offset for utf-8 0xc3 block as discussed in issue #153. I'm also quite sure that it's correct without the -32 offset and added index numbers in the new fonts comments inside the array to make it easier to see whats going on.
Without that fix I had already seen wrong characters with the normal font (i.e. 'ß' 0xc39f) in the german translation which are gone if the offset is removed.

I think that the font problems mentioned in issues #153, #154 and #159 are all related in some way other than the firmwares code. When you actually use the new font by changing the comment in OLED.c the data gets included in the binary and that seems to somehow corrupt the whole font display. In my case it looks like most of the characters in the normal font get replaced with solid blocks.
I searched for a reason why this occurs and found that this behaviour changes if I remove the const declaration for the small fonts array, effectively pushing it to RAM I think.
I have no real idea what's happening here but I thought it might be useful to write it down here.

You can try this non const hack out by compiling https://github.com/matmemo/ts100/commit/2f781986c00f6274c3c67f9d57387d55c5a63a23 with "make lang=DE" which also includes some small characters from the extended range in the german translations for the settings screen.

### CODE REVIEW

**Comment by jonnieZG** [comment]
@matmemo , I think you might be on to something. I don't know much (yet) about STM32 and its memory structure, but are you guys sure about where the font bitmap array ends up, and is the space big enough to hold it?

It is a different animal, but in Arduino there is a statement in C code called PROGMEM 
And if it indeed is enough, is the code

**Comment by Ralim** [comment]
@matmemo I'll check this out locally over the next few days before I merge this in.
Thank you for performing the conversion of the small font 😄 

@jonnieZG As far as I am aware (and I could be wrong on this), the arm compiler does this automatically to data that is marked as `const`. Though I haven't checked this personally.
You can see the expected static ram usage at compile time. Without pulling this request the firmware is using ~15k of the 20k of SRAM in the STM32. I do try and keep an eye on this usage as the firmware expands outwards :) Note that this includes the stack room etc as these are actually hidden in the block of ram statically allocated to Free RToS. (So while it says 15k used, some of this is not used as I've just allocated large stacks for all the *threads*).

**Comment by matmemo** [comment]
@Ralim Thanks, that's good to hear. I feel that the pull request was a bit early on my part as it muddles up quite a few things like the font data, whitespace cleanup in all of Font.h, integration in OLED.cpp, the character offset thing and some theory about the garbled font output in the comment.

After the problems I encountered with #172 are solved I'd like to reformat this pr a bit to make it easier to follow. I'm not very familiar with github so I'm not sure how to go about it. Can you close this pull request?

My idea is to make a new pull request for the font. First simply commiting the new data, then commiting the whitespace cleanup and finally removing the old ASCII_6x8 data and enabling it in OLED.cpp.

Another pull request could contain the python script to generate the font if you're interested to have it in the repo (also I've thought about adding the CasioNostalgia.zip, but I'm unsure if that would be ok with the authors license and the font struct site). I've placed it in "Development Resorces/fonts" in my branch but maybe another location would be better?

Finally there is this character offset thing in OLED.cpp, which I think should be changed but don't know how you think about that and if I should make that another pr?

Ok, that's it. And sorry for asking that many questions...

**Comment by Rockman18** [comment]
Since #173 is pulished, I think you can close this pull request. 
Close button at the bottom of the page ! or delete the branch on your repo !

**Comment by matmemo** [comment]
@jonnieZG thanks for the input! Luckily this issue seems be solved and there is even some remaining space in the chips flash rom :)
I had a similar train of thought when I was trying to find the reason for the problem. In addition to what Ralim said in the above comment you can look up where everything goes by using "arm-none-eabi-objdump -x" on the compiled TS100_xx.elf file to get a listing of the containing sections and objects with their positions inside the target binary. Data declared as const gets copied (by the linker according to the linker script) into the .rodata section while non const goes into .data which I believe to get copied into ram (beginning at 0x2000000) at startup time. At runtime the flash rom is mapped into the address space beginning at 0x8000000 on the stm32 and can be adressed directly. Since I'm also new to the stm32 take this with a grain of salt but it's what I've found so far ;)
 
@Rockman18 ok, I'll do that, thanks!

**Pull request closed without merging**
