### PR TITLE
French Translation - Double Line Mode

### PR DESCRIPTION
**Pull request by Rockman18**

### CODE REVIEW

**Comment by Rockman18** [comment]
Please check the commit because I can't manage to compile the sources on System Workbench for STM32. Even before my commit, I don't know how to compile the sources. It's the first time I use this IDE for C code.

**Comment by Mrkvozrout** [comment]
Hi, thanks for picking my 2 line menu style so fast :)

The `#define` directives for languages is in `Translation.h` file. If you have the System Workbench for STM32, you can build the project with `Project`->`Build project` or with a hammer icon in tool bar.

**Comment by Rockman18** [comment]
Thanks @Mrkvozrout.

Yes, the #define should be there but it isn't anymore since last commit "Update Makefile and build script". Go check !!!

**Comment by Mrkvozrout** [comment]
Right, I missed the last change. I tested it now and you can localy re-add the lang definition in `Translation.h` (I guess anywhere) and then it will build with your language, default ir EN.

**Pull request closed without merging**
