### PR TITLE
 Add Fahrenheit management for SleepTemp && Improve swithing °C -> °F

### PR DESCRIPTION
**Pull request by Rockman18**
**Add Fahrenheit management for SleepTemp && Improve swithing °C -> °F**
- Change step from 10 to 20 for fahrenheit (quite same step number to
make a loop in °C or °F). It was really long too make the loop before
- Create a check for min temperature. When switching from °C -> °F
temperatures in memory stay in °C so they can be too low

**Refactoring Fahrenheit or Celsius symbol display**

TODO : Convert temperature in memory (SleepTemp & BoostTemp) when unit
is switched or reset temperatures to specific default value, to avoid
bugs when soldering. If I choose 840°F for boost mode then I switch to °C, what happen when I start boost mode for 840°C ????

### CODE REVIEW

**Comment by Ralim** [comment]
I'll openly admit I've sort of avoided Fahrenheit work as I don't use it. (Not in the USA).

I'm happy to pull this in, would you like me to wait for you to have a crack at the todo point ?

**Comment by Rockman18** [comment]
I understand I'm French and not really friendly with Fahrenheit too...
I'll try to code the missing improvements during my holidays. If I don't have time, I'll tell you to merge

**Comment by Ralim** [comment]
Its up to you, just let me know and ill pull it in :)

**Comment by Ralim** [comment]
@Rockman18 How did you go with this ? (No Rush)

**Comment by Ralim** [comment]
I'm going to close this as this #264  is working on this now and should be close to done.

**Pull request closed without merging**
