### PR TITLE
Update Translation.c

### PR DESCRIPTION
**Pull request by lfhohmann**
New Portuguese Brazil translation

### CODE REVIEW

**Comment by federck** [comment]
Hi there,
I've noticed that some of your translations exceed the number of characters permitted by the display (Eg.: each word in «{"Temperatura", "repouso"}» option should be at most 9 characters long)

**Comment by Ralim** [comment]
Ill wait for @lfhohmann to get back to this with new sizings and then ill merge it :)

**Comment by Ralim** [comment]
@lfhohmann Any chance you have managed to revise this to fit in the length requirements?

**Comment by SmayK** [comment]
hello, small contribution on translation for French, here they are:

```
const char* SettingsCalibrationWarning = "Assurez-vous que la panne soit à température ambiante avant de continuer!";
const char* SettingsResetWarning = "Voulez-vous vraiment réinitialiser les paramètres aux valeurs d'usine?";
const char* UVLOWarningString = "DC FAIBLE";            // <=8 chars
const char* UndervoltageString = "Sous-tension";     // <=16 chars
const char* InputVoltageString = "V d'entrée: ";        // <=11 chars, preferably end with a space
const char* WarningTipTempString = "Temp. Panne: ";     // <=12 chars, preferably end with a space
const char* BadTipString = "PANNE HS";                // <=8 chars
const char* SleepingSimpleString = "Zzzz";              // Must be <= 4 chars
const char* SleepingAdvancedString = "En veille...";    // <=16 chars
const char* WarningSimpleString = "HOT!";               // Must be <= 4 chars
const char* WarningAdvancedString = "ATTENTION! CHAUD"; // Must be <= 16 chars
const char* SleepingTipAdvancedString = "PANNE:";      // <=6 chars
const char* IdleTipString = "PANNE:";     // IdleTipString+IdleSetString <= 10
const char* IdleSetString = " Set:";    // preferably start with a space; IdleTipString+IdleSetString <= 10
const char* TipDisconnectedString = "PAS DE PANNE!"; // <=16 chars
const char* SolderingAdvancedPowerPrompt = "Puissance: ";
```

**Comment by SmayK** [comment]
hello, do not know how works this citeje gives here my little contribution on the translation for the French, here it is:

`const char* UVLOWarningString = "V FAIBLE";            // <=8 chars`

**Comment by Ralim** [comment]
@SmayK Please open a new issue with your translated content in it.

Please post your translation of this 

```
#ifdef LANG_EN

const char* SettingsDescriptions[17] = {
  // These are all the help text for all the settings.
  // No requirements on spacing or length.
  /* Power source (DC or batt)          */ "Power source. Sets cutoff voltage. <DC 10V> <S 3.3V per cell>",
  /* Sleep temperature                  */ "Sleep Temperature <C>",
  /* Sleep timeout                      */ "Sleep Timeout <Minutes/Seconds>",
  /* Shutdown timeout                   */ "Shutdown Timeout <Minutes>",
  /* Motion sensitivity level           */ "Motion Sensitivity <0.Off 1.least sensitive 9.most sensitive>",
  /* Temperature in F and C             */ "Temperature Unit <C=Celsius F=Fahrenheit>",
  /* Advanced idle display mode enabled */ "Display detailed information in a smaller font on the idle screen.",
  /* Display rotation mode              */ "Display Orientation <A. Automatic L. Left Handed R. Right Handed>",
  /* Boost enabled                      */ "Enable front key enters boost mode 450C mode when soldering",
  /* Boost temperature                  */ "Temperature when in \"boost\" mode",
  /* Automatic start mode               */ "Automatically starts the iron into soldering on power up. T=Soldering, S= Sleep mode,F=Off",
  /* Cooldown blink                     */ "Blink the temperature on the cooling screen while the tip is still hot.",
  /* Temperature calibration enter menu */ "Calibrate tip offset.",
  /* Settings reset command             */ "Reset all settings",
  /* Calibrate input voltage            */ "VIN Calibration. Buttons adjust, long press to exit",
  /* Advanced soldering screen enabled  */ "Display detailed information while soldering",
  /* Description Scroll Speed           */ "Speed this text scrolls past at",
};

const char* SettingsCalibrationWarning = "Please ensure the tip is at room temperature before continuing!";
const char* SettingsResetWarning = "Are you sure to reset settings to default values?";
const char* UVLOWarningString = "DC LOW";            // <=8 chars
const char* UndervoltageString = "Undervoltage";     // <=16 chars
const char* InputVoltageString = "Input V: ";        // <=11 chars, preferably end with a space
const char* WarningTipTempString = "Tip Temp: ";     // <=12 chars, preferably end with a space
const char* BadTipString = "BAD TIP";                // <=8 chars
const char* SleepingSimpleString = "Zzzz";           // Must be <= 4 chars
const char* SleepingAdvancedString = "Sleeping...";  // <=16 chars
const char* WarningSimpleString = "HOT!";            // Must be <= 4 chars
const char* WarningAdvancedString = "!!! TIP HOT !!!"; // <=16 chars
const char* SleepingTipAdvancedString = "Tip:";      // <=6 chars
const char* IdleTipString = "Tip:";     // IdleTipString+IdleSetString <= 10
const char* IdleSetString = " Set:";    // preferably start with a space; IdleTipString+IdleSetString <= 10
const char* TipDisconnectedString = "TIP DISCONNECTED"; // <=16 chars
const char* SolderingAdvancedPowerPrompt = "Power: ";

const char SettingRightChar = 'R';
const char SettingLeftChar = 'L';
const char SettingAutoChar = 'A';

const char SettingFastChar = 'F';
const char SettingSlowChar = 'S';

const enum ShortNameType SettingsShortNameType = SHORT_NAME_DOUBLE_LINE;
const char* SettingsShortNames[17][2] = {
  /* (<= 11) Power source (DC or batt)          */ {"Power", "source"},
  /* (<=  9) Sleep temperature                  */ {"Sleep", "temp"},
  /* (<=  9) Sleep timeout                      */ {"Sleep", "timeout"},
  /* (<= 11) Shutdown timeout                   */ {"Shutdown", "timeout"},
  /* (<= 13) Motion sensitivity level           */ {"Motion", "sensitivity"},
  /* (<= 13) Temperature in F and C             */ {"Temperature", "units"},
  /* (<= 13) Advanced idle display mode enabled */ {"Detailed", "idle screen"},
  /* (<= 13) Display rotation mode              */ {"Display", "orientation"},
  /* (<= 13) Boost enabled                      */ {"Boost mode", "enabled"},
  /* (<=  9) Boost temperature                  */ {"Boost", "temp"},
  /* (<= 13) Automatic start mode               */ {"Auto", "start"},
  /* (<= 13) Cooldown blink                     */ {"Cooldown", "blink"},
  /* (<= 16) Temperature calibration enter menu */ {"Calibrate", "temperature?"},
  /* (<= 16) Settings reset command             */ {"Factory", "reset?"},
  /* (<= 16) Calibrate input voltage            */ {"Calibrate", "input voltage?"},
  /* (<= 13) Advanced soldering screen enabled  */ {"Detailed", "solder screen"},
  /* (<= 11) Display Help Text Scroll Speed     */ {"Description","Scroll Speed"},
};

const char* SettingsMenuEntries[4] = {
/*Soldering Menu*/"Soldering\nSettings",
/* Power Saving Menu*/"Sleep\nModes",
/* UI Menu*/"User\nInterface",
/* Advanced Menu*/"Advanced\nOptions", };
const char* SettingsMenuEntriesDescriptions[4] ={
"Soldering settings",
"Power Saving Settings",
"User Interface settings",
"Advanced options"
};
#endif
```

**Comment by SmayK** [comment]
sorry I am a little lost in the operation of the city.
he is here my french translation

https://github.com/SmayK/ts100/blob/master/Update%20Translation.c

**Comment by SmayK** [comment]
I created a new issue, I hope that's how it should be done

**Comment by Ralim** [comment]
Yep that's it, sorry I didn't get back to you.
I'll merge in your update in the next update I push out soon.

**Comment by SmayK** [comment]
OK no worries, it leaves time for my ts100 iron arrives at home. I am pleased to participate at my level.

**Pull request closed without merging**
