### PR TITLE
Add autocompilation after push with GitHub Actions

### PR DESCRIPTION
**Pull request by playday3008**
If you want, you can merge this to autocompile your project automatically

### CODE REVIEW

**Comment by Ralim** [comment]
Hi, I'm already using codeship to automatically build the project and notify me if builds fail.
What would the benefit be here to use this instead?

**Comment by Ralim** [comment]
Hi, if you could clean this up to not run the ls command or to upload artifacts by default this could be interesting to test. Have you been running it on other repositories?

**Comment by playday3008** [comment]
> Hi, if you could clean this up to not run the ls command or to upload artifacts by default this could be interesting to test. Have you been running it on other repositories?

I have 8 repos with autocompilation, I fork your repo because I want to fix Ukrainian language and autocompile firmware, I don't want to install dependencies and WSL or linux, to compile firmware on my PC

**Comment by playday3008** [comment]
if you want autocompilation without my tries (commits), just copy this file https://github.com/playday3008/ts100/blob/master/.github/workflows/ccpp.yml to you repo

**Comment by playday3008** [comment]
And, if someone do pull request to you repo, GitHub automatically try to compile your code with changes from request, and check compatibility

**Comment by playday3008** [comment]
Ex. https://github.com/android-hacker/VirtualXposed/pull/798/checks?check_run_id=434894306
I create pull request, and GitHub automatically try compile

**Comment by playday3008** [comment]
> What would the benefit be here to use this instead?

Anyone can check compilation status, and anyone can check pull request compatibility

**Comment by Ralim** [comment]
Ah okay so this does do the same thing as my gitlab and codeship stuff but just publicly 😅

I'm not against your commits  just checking I understand if it's doing anything odd or extra.

I will merge this if your happy with it (noting a lot of edits) 😅

Happy to add extra CI, it's always good :)

**Pull request merged**
