### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by federck**

### CODE REVIEW

**Comment by Ralim** [comment]
Have you confirmed this still fits?

**Comment by Mrkvozrout** [comment]
@Ralim Exactly my thoughts :)

I have just checked the the string lengths and... well

- currently there is enough space in all languages for this one extra char

but

- Italian is at max length without spacing
- generally this takes out one precious char from translators
- this is for `gui_showTipTempWarning` but there is also `gui_SolderingSleepingMode` with small font where there is not enough space for this and thus would be inconsistent

So currently I do not recommend to do this.

Ideally single symbol for °C/°F should be used for this (as with the big font) but another font section for small symbols would need to be added and to design this small symbol is not much satisfactory:

- °C `0x03,0x03,0x38,0x44,0x44,0x28`, °F `0x03,0x03,0x00,0x7C,0x14,0x04`
screenshot-2018-1-9 ts100 font editor screenshot-2018-1-9 ts100 font editor 3

- °C `0x02,0x05,0x72,0x88,0x88,0x50`, °F `0x02,0x05,0x02,0xF8,0x28,0x08`
screenshot-2018-1-9 ts100 font editor 1 screenshot-2018-1-9 ts100 font editor 4

- °C `0x02,0x05,0x32,0x48,0x48,0x00`, °F `0x02,0x05,0x7A,0x28,0x08,0x00`
screenshot-2018-1-9 ts100 font editor 2 screenshot-2018-1-9 ts100 font editor 5

**Comment by Mrkvozrout** [comment]
I also tested adding `°` to values of Temp Unit menu option
- using `°` instead of space is not good when single line menu is used (double line menu is kind of ok with it)
- using single symbol (as when soldering) does not look good in menu because it is small (so maybe make it bigger? )

**Comment by Ralim** [comment]
Going to close this as it causes issues under some languages and would require further work to implement.
Re-open this if further work is done.

**Pull request closed without merging**
