### PR TITLE
Fast menu scroll

### PR DESCRIPTION
**Pull request by jonnieZG**
Menu description scrolling is now 3x faster.

### CODE REVIEW

**Comment by Ralim** [comment]
Hey,
When the text is sped up on the description scrolling it starts to tear, which is why it is currently running at this rate.
Happy to merge everything but the text speed changes, since I don't want the tearing as it makes it uncomfortable to read.

have you tested this on your iron?

**Comment by Mrkvozrout** [comment]
The descriptions do tear even with current speed on my iron :)

**Comment by jonnieZG** [comment]
Yes, I have tested it, and personally, I find the tearing, compared to the sssllloooowwww scrolling, being lesser of the two evils. [Here](https://www.dropbox.com/s/wgz49r664hiqwft/20180305_093921.mp4?dl=0) is the footage, but bear in mind that the camera also induces some additional tearing to the scrolling text.

**Comment by jonnieZG** [comment]
Hey, @Ralim, check this out: I've changed the offset function a bit, so it has less tearing now. [Here](https://www.dropbox.com/s/gufwbnk77ns6k6n/20180305_100629.mp4?dl=0) is the new video. Still not perfect, but much better than the first version.

```
int16_t descriptionOffset = ((((HAL_GetTick() - descriptionStart)
					/ 20) % (maxOffset * 2))) * 6;
```

**Comment by jonnieZG** [comment]
Update, guys - tearing is significantly reduced now. I've changed the scrolling routine to update the screen only when required. Until now, the screen was cleared/redrawn on each pass, even when not required, which caused unnecessary flickering and tearing. Check it out [here](https://www.dropbox.com/s/1ch2z86qjehok5a/20180305_104327.mp4?dl=0).

**Comment by Mrkvozrout** [comment]
I will try it when I get home :) For me the speed is not that important, because typically user will read it once (or just a few times) and then just know what the menu item does.

**Comment by Ralim** [comment]
Thank you @jonnieZG.
I was about to come back and suggest that the updating causes the tearing so we could change to draw on change or change update rate, but you already figured that you 😄 Thank you for beating me to it !

**Comment by Mrkvozrout** [comment]
I dont like to say it, but even with current state the tearing and fast text rolling make it really uncomfortable to read descriptions. 

Also I think with this speed some of the more descriptive texts (with enumerated values, or description of power source setting) may be quite hard to catch, if you already dont know, what the option does.

**Comment by jonnieZG** [comment]
@Mrkvozrout, did you try it your actual device, or just relying the footage that I posted? As I said, the camera induces extra flickering, so you have to see it in real life. After I did the change, at least for me, I don't find it to be uncomfortable or too fast to read (and I am quite picky about these things). ;)

**Comment by Mrkvozrout** [comment]
@jonnieZG I tested it on real device, I don't like this speed to be fixed, but I am fine with configurable speed with lower as default (slower speed is handy for new users, after they get familiar with the options they can rise it) :)

I wonder if it looks the same on my device as on yours (from the video it's hard to tell.. maybe 60FPS video would be better). Or do we have different hardware? Or is it just me slow sensing? :)

**Comment by jonnieZG** [comment]
As @Mrkvozrout pointed out, clearing and redrawing the screen in this particular case should not affect the display, since the display is actually updated by OLED::refresh() method. What I further improved in #221 is that I added a parameter that specifies speed (higher the value -> lower the speed) and calling the OLED::refresh() only when a change occurred.

**Pull request merged**
