### PR TITLE
Add czech translation

### PR DESCRIPTION
**Pull request by Mrkvozrout**
Added czech translation (locale cs_CZ)

### CODE REVIEW

**Comment by Mrkvozrout** [comment]
Hi I created czech translation which I want to contribute.  It is without dacritics so only basic characters are used (I hope diacritics can be added later). I made a lot of effort to make it as short and as descriptive as possible.

I compared with english texts on the real thing and found out some additional constraints to those in ending line comments:

- SettingsCalibrationWarning - when this warning is rolling on the screen, the first char immediatelly follows the last char, so I added an extra space
- WarningAdvancedString - is this the text showed on detailed cooling screen? If so there are only 16 chars shown with no rolling so even in your english translation the last **!** is missing

**Comment by Mrkvozrout** [comment]
Forgot to check the sleeping texts, will do tomorrow :)

**Comment by jonnieZG** [comment]
I have just added a fix to issue #132, with addition to the font, containing letters from range U+0100 to U+017F. When it gets applied, you can use all your diacritics.

**Comment by Mrkvozrout** [comment]
@jonnieZG great work, I will prepare the proper check version then

**Comment by Mrkvozrout** [comment]
I managed to build the firmware with my translation and flash it to my TS100. Tested it and did small adjustments.

**Comment by jonnieZG** [comment]
@Mrkvozrout Jan, did you try with the new Latin-1 font and the diacritics?

**Comment by Mrkvozrout** [comment]
@jonnieZG Not yet, I just polished ( :D ) the texts as I managed to upload it to real device. I will definitelly look at your changes and try the diacritics later.

Any special steps to take, or is it just copy-paste and it works?

**Comment by jonnieZG** [comment]
It should be just copy/paste on the two changed files. I haven't installed the compiler yet, so I couldn't test it. According to my experience, it should work, but I must be honest and point out that I didn't get to test it. I am just not sure about the size of the compiled code, because the change adds extra 768 bytes on account of the extra characters.

**Comment by Mrkvozrout** [comment]
@Ralim What is the maximum memory limit for the complete firmware? I can see the BIN file has 39kB and I found a comment in `LinkerScript.ld` that ROM is 48K minus 2 pages (settings and logo) so currently there is something over 6K of free memory left?

**Comment by Ralim** [comment]
Yep.
You're correct in your deductions :)
Which is why I'm not optimising font tables etc just yet :)

I'll be merging this soon when Im on my dev machine.

**Pull request merged**
