### PR TITLE
Update Settings.h

### PR DESCRIPTION
**Pull request by Adrianotiger**
Options are 7 now

### CODE REVIEW

**Comment by Ralim** [comment]
Thanks. I'll push out a release shortly

**Comment by Adrianotiger** [comment]
Wow, that was fast! Thank you for your work!

**Comment by Ralim** [comment]
New release pushed :)

**Comment by Adrianotiger** [comment]
It works like expected now (lefty)! Thanks :D I have 8 menu settings (forget my edit in the last post).

**Comment by Ralim** [comment]
No problem at all. 
I feel bad for completely mind blanking and forgetting to update the variable.
Hopefully you can enjoy it now :)

**Pull request merged**
