### PR TITLE
added dutch translation

### PR DESCRIPTION
**Pull request by L0laapk3**
- [x] The commit message make sense
- [ ] The changes have been tested locally
- [ ] New features have been documented in the Wiki
- [x] I'm willing to maintain this in the future (Totally Optional) **(maybe)**

* **What kind of change does this PR introduce?** 
Dutch language

### CODE REVIEW

**Comment by daborbor** [comment]
I would change `"Temperatuur laten flikkeren in het hoofdmenu als de soldeerpunt aan het afkoelen is." `to 
`"Temperatuur laten knipperen in het hoofdmenu als de soldeerpunt aan het afkoelen is."`.

I would change 
`+const char* WarningSimpleString = "WARM!";
+const char* WarningAdvancedString = "!!! TIP WARM !!!"; `

to 
`
+const char* WarningSimpleString = "HEET!"; 
+const char* WarningAdvancedString = "!!! PUNT HEET!!!"; 
`
I also think that it's better to call the tip 'punt' in Dutch. What do you think about it?

**Comment by yschaeff** [comment]
I reviewed it too. +1 to all @daborbor 's feedback.

**Comment by L0laapk3** [comment]
I'll take some of your points, but I'll keep flikkeren ;) it sounds more right in my opinion, maybe because I'm from belgium :p

As for "punt", I had originally used it everywhere, but it just ended up sounding weird to me where I didn't have enough room to use "soldeer" infront of it. So I decided to use "tip" instead in the shorter strings since both words have the same meaning.

**Comment by yschaeff** [comment]
> maybe because I'm from belgium :p

That explains why some phrases sounded a bit off to me but I couldn't point my finger at the problem. Cheers than, and as a user thank you for your language contribution.

**Comment by L0laapk3** [comment]
Whoops, that is indeed not correct. Dat was een beetje slordig van me ;)
Now everything should be up to par.

**Comment by L0laapk3** [comment]
Is there any problem with this thats the reason for it not making it into the release? If theres something wrong, Ill be happy to have a look at it.

**Comment by Ralim** [comment]
One of a couple that didnt want to build and fit on my desktop, and I'm revisiting these in a few days on my linux machine when I have it back up and running to get builds back to normal.

**Pull request merged**
