### PR TITLE
Description scroll speed parametrized + smooth scroll in userConfirmation

### PR DESCRIPTION
**Pull request by jonnieZG**
Message scrolling speed can now controlled by a variable **scrollingSpeedFactor**. Higher values result in slower scrolling speed. Currently set to 4, resulting in about 1 second per screen.

Smooth scrolling is also implemented for userConfirmation (on *Factory Reset* and *Temperature Calibration*).

Besides the small cleanup that makes the offset calculation more readable and intuitive, this can be used as a preparation for setting the description scrolling through a User Interface menu (#214).

### CODE REVIEW

**Comment by Mrkvozrout** [comment]
I have also rewritten it in a similar way, but you were faster :) FYI I used 5 as the factor which was the limit for me and the tearing was clearly visible.

**Comment by Ralim** [comment]
I get busy for a few days and miss dozens of messages 😃 
Another thing to consider here, is that the actual write speed to the LCD I can probably update significantly, however this wont change the fact that the OLED screen itself has its own refresh rate (That I don't think i can make faster).

@jonnieZG Does this completely replace #220 ? If so can you close that one :)

Thank you both for all of your work on this, i really do appreciate it.
I'm currently testing ideas locally to split the menu into having submenu's ( #214 ), and so would be happy to add an option for scroll speed if you feel its something thats worth having adjustable

**Comment by Mrkvozrout** [comment]
@Ralim I am curious, how the submenus will come out :) I think it is worth having adjustable speed - I suggest having lower speed that looks perfect (no tearing) as default. Then anyone can speed it up if needed.

**Comment by jonnieZG** [comment]
@Ralim, #220 is a separate branch limited just to the HR translation issues. It is unrelated to this issue, since I try to use a separate branch for each feature or issue.

**Comment by jonnieZG** [comment]
@Mrkvozrout, it is likely that you have a different display, since at 5 the scrolling on my iron is really smooth. Another thing: did you observe your display at natural daylight, or under artificial (LED or neon) lights? The latter can induce the flickering effect, due to the light strobing.

**Comment by Ralim** [comment]
All the displays have a variation in their refresh rate which is also slightly temperature dependent as well. One of my units flickers alot more than all the others.
 I asked about #220 because you have included its commits in this patch as well. That's okay then since the squash will remove them but just wanted to check.

I'm happy to merge this now and leave coming up with a menu option for the speed to come with layered menus. 
Also remembering that some languages are more sensitive to reading time than others, so before going too fast we need to see how it goes across different languages.

**Pull request merged**
