### PR TITLE
Looking at i2c

### PR DESCRIPTION
**Pull request by Ralim**
This is a fun PR of cleaning up a bunch of the logic for I2C.

This was some long overdue techdebt to clean up, motivated by the issue I ran into in the last release.
(As spotted by @paulfertser [here](https://github.com/Ralim/ts100/commit/3d3799d4143b213d7e5b455e2a8c2126582b7410#commitcomment-42027931))

After the cleanup a fun race on the irq for the pd setup was found (and fixed), and also took this time to move all of the I2C peripheral initalisation into the respective threads.

Also killing off some unused logic in the PD stack for some flash room back

### CODE REVIEW

**Comment by paulfertser** [comment]
This looks like a nice clean-up to me. I had a look and couldn't spot any obvious issues but I want to share some related thoughts brought to mind:
1. FreeRTOS has a special way to help with initialisation: when configUSE_DAEMON_TASK_STARTUP_HOOK is enabled it calls vApplicationDaemonTaskStartupHook() (user function) from Timers-handling task (just once on startup, before it starts caring about the timers); the tasks can also be created on-the-fly, from within this function; this doesn't directly apply to this project as it doesn't use FreeRTOS timers at all, and so the corresponding task is disabled;
2. I recommend to never assume that any ST HAL function is thread-safe. I once had hard time debugging an issue with incorrect GPIO initialisation only to find out that one task was configuring its relevant pins, and another was configuring another set of pins (on the same PORT), but since the tasks had same priority and preemption enabled those were getting mixed up. And the problem was exposed by a completely unrelated code change, as it usually happens with the nastiest bugs; at least this one was easily reproducible. Of course, that's valid not only for GPIO peripherals but for all shared resources, as many read-modify-write operations (plenty of them used during initialisations) are not atomic.

**Comment by Ralim** [comment]
Interesting point about 1, I've never used timers in FreeRToS much really; Have always used hardware timers for various reasons so far 😅 That is a good initalisation point though. hmmm..

Well aware of 2,bitten enough times yet it still catches me out _sigh_...
Its sort of why I wrapped up the I2C earlier on, but this was more fun to unwrap than originally expected.
I did try and put most of the init earlier on in the setup flow to prevent these kinds of races... Tried 🤣

**Comment by paulfertser** [comment]
For initialisation you can just create a dedicated initialisation task, do the init, create the other tasks from it, and exit. At least that's how I understood some advices found on their web forum.

**Comment by Ralim** [comment]
Yeah, sometimes I spawn all the init off a background task that gets used for other work, but i tend not to make an init task when using static allocation as recycling the stack can be annoying :/

**Pull request merged**
