### PR TITLE
Update translation_uk.json

### PR DESCRIPTION
**Pull request by playday3008**
Don't merge now, I have some questions

What is "T","S","F","O" here:

		"SettingStartSolderingChar": "T",
		"SettingStartSleepChar": "S",
		"SettingStartSleepOffChar": "O",
		"SettingStartNoneChar": "F"
F - False?
O - Off?
S - Sleep?
T - True?

### CODE REVIEW

**Comment by Ralim** [comment]
`SettingStartSolderingChar` -> Start into full power on
`SettingStartSleepChar` -> Start into sleep mode with heater set to idle temp
`SettingStartSleepOffChar` -> Start into sleep mode but heat off until move
`SettingStartNoneChar` -> Start in soldering off mode (ie main screen)

**Comment by playday3008** [comment]
What do `PowerPulsePower` and `TipGain`?

**Comment by Ralim** [comment]
`PowerPulsePower ` To keep a power bank alive the iron will occasionally pulse the tip a little bit to draw power. PowerPulsePower  sets the watts used for the pulse

`TipGain` us the uV per degree C value for the tip. Allows adjusting the tip sensitivity to adjust for tip to tip differences.

**Comment by playday3008** [comment]
IDK how to correctly translate `TipGain` to Ukrainian lang. (

**Comment by Ralim** [comment]
Ah, hmm. I don't really know how to help with that :|

**Comment by Ralim** [comment]
@playday3008  Do you want this merged in as-is?

**Comment by playday3008** [comment]
Not now

**Comment by playday3008** [comment]
Merge as-is (

**Pull request merged**
