### PR TITLE
Add utf-8 capable 6x8 pixel small font (redone)

### PR DESCRIPTION
**Pull request by matmemo**
This pull request contains all necessary changes to include an utf-8 capable 6x8 font.

The font data is based upon the CasioNostalgia font by zdimension found here:
https://fontstruct.com/fontstructions/show/1193786/casionostalgia

This is a cleaned up version of pr #170 and should be easier to follow.

### CODE REVIEW

**Comment by Rockman18** [comment]
Hello @matmemo, Thanks a lot, it's perfect !!!
I've tryed your branch last night with my French translation. Everything works perfectly. 
@Ralim IMO you should merge this ASAP !

**Comment by matmemo** [comment]
Hi @Rockman18, thanks a lot! I'm happy to hear that :)

**Comment by jonnieZG** [comment]
Line 758 in Font.h has to be changed as follows, in order to support Croatian, Serbian, Bosnian and Slovenian:
```C++
		0x38, 0x44, 0x44, 0x4A, 0x7F, 0x00,    // 068: 'd' U+0064 (utf-8: 64)
```

**Comment by Ralim** [comment]
I'm going to merge this happily :)
@jonnieZG  Can you create a pull request please :)

**Pull request merged**
