### PR TITLE
Update Translation.cpp

### PR DESCRIPTION
**Pull request by fishingpro**
Made a normal Russian translation.
On 256 line there was an error instead of "const" was "cconst", perhaps for this reason the Russian assembly is buggy and often turns off.

Hmm .. 256 wonderful number :)

Sincerely, Denis Goncharov.

### CODE REVIEW

**Comment by federck** [comment]
Hi there, 
I've noticed that you filled "settings name" form wrongly.
For two lines menu please feel free to translate this one (keeping in mind the limit of characters specified at the start of each line): 
```
const enum ShortNameType SettingsShortNameType = SHORT_NAME_DOUBLE_LINE;
const char* SettingsShortNames[17][2] = {
  /* (<= 11) Power source (DC or batt)          */ {"Power", "source"},
  /* (<=  9) Sleep temperature                  */ {"Sleep", "temp"},
  /* (<=  9) Sleep timeout                      */ {"Sleep", "timeout"},
  /* (<= 11) Shutdown timeout                   */ {"Shutdown", "timeout"},
  /* (<= 13) Motion sensitivity level           */ {"Motion", "sensitivity"},
  /* (<= 13) Temperature in F and C             */ {"Temperature", "units"},
  /* (<= 13) Advanced idle display mode enabled */ {"Detailed", "idle screen"},
  /* (<= 13) Display rotation mode              */ {"Display", "orientation"},
  /* (<= 13) Boost enabled                      */ {"Boost mode", "enabled"},
  /* (<=  9) Boost temperature                  */ {"Boost", "temp"},
  /* (<= 13) Automatic start mode               */ {"Auto", "start"},
  /* (<= 13) Cooldown blink                     */ {"Cooldown", "blink"},
  /* (<= 16) Temperature calibration enter menu */ {"Calibrate", "temperature?"},
  /* (<= 16) Settings reset command             */ {"Factory", "reset?"},
  /* (<= 16) Calibrate input voltage            */ {"Calibrate", "input voltage?"},
  /* (<= 13) Advanced soldering screen enabled  */ {"Detailed", "solder screen"},
  /* (<= 11) Display Help Text Scroll Speed     */ {"Description","Scroll Speed"},
};
```

**Comment by fishingpro** [comment]
Thank you, really did not understand. You really helped. Made corrections. Now all the lines have a valid length.

**Comment by federck** [comment]
That's right, probably @Ralim will want to put the finishing touch on it before merging, but that's it.
Thank you :)

**Comment by fishingpro** [comment]
I'm waiting for this update in the first place, because in the main branch on the 256th line(Translation.cpp) of the grammatical error "cconst" instead of "const" - it's bad :)

**Comment by Ralim** [comment]
@fishingpro I know about the cconst typo, but it wasnt worth pushing a new commit to remove the one letter so i just did it before the local builds. (Otherwise there wouldnt be a Russion firmware released).
I was just going to inline that fix with the next commit I make to this repo.

I'll merge this in shortly

**Comment by fishingpro** [comment]
Tell the creator, is there any manual for assembling the firmware on Eclipse? Simply put, what do me need to do to get the file .hex?

**Comment by Mrkvozrout** [comment]
@fishingpro Get the [SW4STM32](http://www.st.com/en/development-tools/sw4stm32.html) (Eclipse based IDE)

**Comment by fishingpro** [comment]
OMG, this is a dislocation of the brain, I'll put the ice to my head and continue reading ... there seems to be more haemorrhoids than with AVR and PIC-controllers.

**Comment by fishingpro** [comment]
So what next, next, next, open the project, Ctrl-F9 does not happen?)))

**Comment by Ralim** [comment]
You need to import the existing project into your workspace.
This can be done through right clicking in the project list area on the left or through the file menu. Same as normal eclipse. 

I use atollic normally for most of my work where I use the IDE or command line for the rest. System workbench is not the best out there, since it's mainly just eclipse, but it's free and works cross platform for others who would like to build the firmware.

**Comment by fishingpro** [comment]
image
I do and always get the same result.

**Comment by Ralim** [comment]
@fishingpro I'm not sure what you mean by your picture?
The makefile is not used by systemworkbench and if its build correctly there is probably a release folder with the EN hex file in it waiting for you ? (look in the same folder as the ts100 project)

**Pull request closed without merging**
